import streamlit as st
from datetime import datetime
import uuid
from fpdf import FPDF
import qrcode
from io import BytesIO
import base64

st.set_page_config(page_title="AI Trust Certificate", page_icon="🛡️", layout="wide")
st.title("🛡️ AI Guardian OS")
st.subheader("AI Trust Score & Certificate")

# Get scores from session state
fairness = st.session_state.get("fairness_score", 90)
privacy = st.session_state.get("privacy_score", 95)
explainability = st.session_state.get("explainability_score", 92)
compliance = st.session_state.get("compliance_score", 91)
quality = st.session_state.get("data_quality_score", 89)

# Calculate Trust Score
trust_score = round(fairness * 0.25 + privacy * 0.20 + explainability * 0.20 + compliance * 0.20 + quality * 0.15)

if trust_score >= 80:
    status = "🟢 APPROVED FOR DEPLOYMENT"
elif trust_score >= 60:
    status = "🟡 REVIEW REQUIRED"
else:
    status = "🔴 REJECTED"

st.markdown("---")

c1, c2, c3 = st.columns(3)
c1.metric("🛡️ AI Trust Score", f"{trust_score}/100")
c2.metric("Fairness", f"{fairness}%")
c3.metric("Privacy", f"{privacy}%")

st.progress(trust_score / 100)
st.success(status)

st.markdown("## Score Breakdown")
st.table({
    "Category": ["Fairness", "Privacy", "Explainability", "Compliance", "Data Quality"],
    "Score": [fairness, privacy, explainability, compliance, quality]
})

st.markdown("---")

# Generate Certificate ID
certificate_id = "AIG-" + str(uuid.uuid4())[:8].upper()

# ==================== PDF CERTIFICATE GENERATOR ====================
def generate_certificate_pdf():
    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.add_page()
    
    # Background border
    pdf.set_line_width(1)
    pdf.rect(15, 15, 180, 267, 'D')  # Outer border
    
    # Header
    pdf.set_font("Helvetica", 'B', 24)
    pdf.cell(0, 20, "AI GUARDIAN OS", ln=True, align='C')
    
    pdf.set_font("Helvetica", 'B', 18)
    pdf.cell(0, 10, "AI TRUST CERTIFICATE", ln=True, align='C')
    
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 10, f"Certificate ID: {certificate_id}", ln=True, align='C')
    pdf.cell(0, 8, f"Generated On: {datetime.now().strftime('%d %B %Y')}", ln=True, align='C')
    
    pdf.ln(10)
    
    # Trust Score - Big & Bold
    pdf.set_font("Helvetica", 'B', 32)
    pdf.set_text_color(0, 100, 0)  # Green
    pdf.cell(0, 20, f"{trust_score}/100", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font("Helvetica", '', 14)
    pdf.cell(0, 10, status, ln=True, align='C')
    
    pdf.ln(10)
    
    # Scores Table
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "Score Breakdown", ln=True, align='C')
    
    pdf.set_font("Helvetica", '', 11)
    categories = ["Fairness", "Privacy", "Explainability", "Compliance", "Data Quality"]
    scores = [fairness, privacy, explainability, compliance, quality]
    
    for cat, score in zip(categories, scores):
        pdf.cell(100, 8, cat, border=1)
        pdf.cell(80, 8, f"{score}%", border=1, align='C', ln=True)
    
    pdf.ln(15)
    
    # Verification QR Code
    qr = qrcode.QRCode(version=1, box_size=3)
    qr.add_data(f"https://ai-guardian.example.com/verify/{certificate_id}")
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    
    img_buffer = BytesIO()
    img.save(img_buffer, format='PNG')
    img_buffer.seek(0)
    
    pdf.image(img_buffer, x=85, y=pdf.get_y(), w=40)
    pdf.ln(45)
    
    pdf.set_font("Helvetica", '', 10)
    pdf.cell(0, 10, "Scan the QR code to verify authenticity", ln=True, align='C')
    pdf.cell(0, 10, "This certificate is automatically generated by AI Guardian OS", ln=True, align='C')
    
    # Signature area
    pdf.ln(20)
    pdf.cell(90, 10, "___________________________", align='L')
    pdf.cell(90, 10, "___________________________", align='R', ln=True)
    pdf.cell(90, 8, "AI Guardian OS", align='L')
    pdf.cell(90, 8, "Authorized Signatory", align='R')
    
    return bytes(pdf.output())

# Display Certificate Preview (text version)
st.markdown("## 📜 AI TRUST CERTIFICATE")
st.info(f"""
**Certificate ID:** {certificate_id}  
**Generated On:** {datetime.now().strftime("%d-%m-%Y")}  
**Overall Trust Score:** {trust_score}/100  
**Status:** {status}
""")

# Download PDF Button
if st.button("📄 Download Professional PDF Certificate"):
    pdf_bytes = generate_certificate_pdf()
    st.download_button(
        label="⬇️ Download AI_Trust_Certificate.pdf",
        data=pdf_bytes,
        file_name=f"AI_Trust_Certificate_{certificate_id}.pdf",
        mime="application/pdf"
    )

st.balloons()
