import streamlit as st
from datetime import datetime
import uuid

st.set_page_config(page_title="AI Trust Certificate", page_icon="🛡️", layout="wide")

st.title("🛡️ AI Guardian OS")
st.subheader("AI Trust Score & Certificate")

# Get scores from previous pages if available
fairness = st.session_state.get("fairness_score", 90)
privacy = st.session_state.get("privacy_score", 95)
explainability = st.session_state.get("explainability_score", 92)
compliance = st.session_state.get("compliance_score", 91)
quality = st.session_state.get("data_quality_score", 89)

# Trust Score
trust_score = round(
    fairness * 0.25 +
    privacy * 0.20 +
    explainability * 0.20 +
    compliance * 0.20 +
    quality * 0.15
)

if trust_score >= 80:
    status = "🟢 APPROVED FOR DEPLOYMENT"
elif trust_score >= 60:
    status = "🟡 REVIEW REQUIRED"
else:
    status = "🔴 REJECTED"

st.markdown("---")

c1,c2,c3=st.columns(3)

c1.metric("🛡️ AI Trust Score",f"{trust_score}/100")
c2.metric("Fairness",f"{fairness}%")
c3.metric("Privacy",f"{privacy}%")

st.progress(trust_score/100)

st.success(status)

st.markdown("## Score Breakdown")

st.table({
    "Category":[
        "Fairness",
        "Privacy",
        "Explainability",
        "Compliance",
        "Data Quality"
    ],
    "Score":[
        fairness,
        privacy,
        explainability,
        compliance,
        quality
    ]
})

st.markdown("---")

certificate_id="AIG-"+str(uuid.uuid4())[:8].upper()

st.markdown("## 📜 AI TRUST CERTIFICATE")

st.info(f"""

### AI Guardian OS

**Certificate ID:** {certificate_id}

**Generated On:** {datetime.now().strftime("%d-%m-%Y")}

---

### Overall Trust Score

# {trust_score}/100

---

✅ Fairness : PASS

✅ Privacy : PASS

✅ Explainability : PASS

✅ Compliance : PASS

✅ Data Quality : PASS

---

### Deployment Status

{status}

---

This certificate is automatically generated by AI Guardian OS after Responsible AI assessment.

""")

certificate=f"""
AI GUARDIAN OS

AI TRUST CERTIFICATE

Certificate ID : {certificate_id}

Trust Score : {trust_score}/100

Fairness : {fairness}

Privacy : {privacy}

Explainability : {explainability}

Compliance : {compliance}

Data Quality : {quality}

Deployment Status : {status}

Generated On : {datetime.now().strftime("%d-%m-%Y")}
"""

st.download_button(
    "📄 Download Certificate",
    certificate,
    file_name="AI_Trust_Certificate.txt",
    mime="text/plain"
)

st.balloons()
