from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.barcodes.qr import QrCodeWidget

from datetime import datetime
import uuid

def generate_certificate(project_name, trust_score, fairness,
                         privacy, explainability,
                         compliance, quality):

    certificate_id = "AIG-" + str(uuid.uuid4())[:8].upper()

    filename = f"{certificate_id}.pdf"

    doc = SimpleDocTemplate(filename,pagesize=A4)

    styles=getSampleStyleSheet()

    title=styles["Title"]
    title.alignment=TA_CENTER

    heading=styles["Heading2"]
    heading.alignment=TA_CENTER

    body=styles["BodyText"]

    elements=[]

    elements.append(Paragraph("AI GUARDIAN OS",title))
    elements.append(Paragraph("AI TRUST CERTIFICATE",heading))
    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"<b>Certificate ID:</b> {certificate_id}",body))
    elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y')}",body))
    elements.append(Paragraph(f"<b>Project:</b> {project_name}",body))

    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"<b>AI Trust Score:</b> {trust_score}/100",body))
    elements.append(Paragraph(f"Fairness : {fairness}",body))
    elements.append(Paragraph(f"Privacy : {privacy}",body))
    elements.append(Paragraph(f"Explainability : {explainability}",body))
    elements.append(Paragraph(f"Compliance : {compliance}",body))
    elements.append(Paragraph(f"Data Quality : {quality}",body))

    elements.append(Spacer(1,20))

    if trust_score>=80:
        status="APPROVED FOR DEPLOYMENT"
    elif trust_score>=60:
        status="REVIEW REQUIRED"
    else:
        status="REJECTED"

    elements.append(Paragraph(f"<b>Status:</b> {status}",body))

    elements.append(Spacer(1,30))

    qr = QrCodeWidget(certificate_id)

    d = Drawing(80,80)

    d.add(qr)

    elements.append(d)

    elements.append(Spacer(1,20))

    elements.append(Paragraph("Generated by AI Guardian OS",heading))

    doc.build(elements)

    return filename
